FROM node:20.12.0-alpine3.19

ARG DATABASE_URL
ARG JWT_SECRET
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG NEXT_PUBLIC_BASE_URL
ARG UPLOADTHING_SECRET
ARG UPLOADTHING_APP_ID
ARG UPLOADTHING_TOKEN
ARG EMAIL_USER
ARG EMAIL_PASS

ENV DATABASE_URL=${DATABASE_URL}
ENV JWT_SECRET=${JWT_SECRET}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
ENV UPLOADTHING_SECRET=${UPLOADTHING_SECRET}
ENV UPLOADTHING_APP_ID=${UPLOADTHING_APP_ID}
ENV UPLOADTHING_TOKEN=${UPLOADTHING_TOKEN}
ENV EMAIL_USER=${EMAIL_USER}
ENV EMAIL_PASS=${EMAIL_PASS}

WORKDIR /app

COPY package* . 
COPY tsconfig.json . 
COPY ./prisma . 


RUN npm install
RUN DATABASE_URL=$DATABASE_URL npx prisma generate

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
